### ISSUE TITLE
Use Sourcery to automatically generate `LinuxMain.swift` with lists of tests

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/HomeKitty#48]
Seems like this is a nice starting point: https://github.com/nodes-vapor/sourcery-templates

**Comment by meghaphone** [comment]
I'd like to try to add support for this! :) Would you mind assigning this to me @BalestraPatrick ?

**Comment by BalestraPatrick** [comment]
Hey @meghaphone! Just invited you as collaborator, feel free to assign it to yourself 👍

**Comment by meghaphone** [comment]
Awesome! Thanks

**Comment by moritzsternemann** [comment]
I'd like to work on this 😄

**Comment by BalestraPatrick** [comment]
Awesome @moritzsternemann, let me know if you need any help!

**Comment by moritzsternemann** [comment]
I never used sourcery before but I guess assuming the command line tool is installed, mentioning the process in README and configuring via `.sourcery.yml' is the way to go here.

**Comment by moritzsternemann** [comment]
While researching this I just found out that with Swift 4.1 the SwiftPM added a command to generate and update the `LinuxMain.swift` (https://github.com/apple/swift-package-manager/pull/1485).
I got it to work with some small adjustments to the test case setup and I think this is a better solution than adding another dependency.

When SwiftPM generates the `LinuxMain.swift` it thinks the [TestCase class](https://github.com/BalestraPatrick/HomeKitty/blob/master/Tests/AppTests/Utilities.swift) is a test case itself and fails because that's an invalid test case name. I changed the class to a protocol and adopted it in all test case files.

Let me know what you think about this solution 🙃

**Comment by BalestraPatrick** [comment]
@moritzsternemann The problem with that as stated in the SPM PR is that it only works on macOS. Our CI runs on Linux on CircleCI so the `LinuxMain` wouldn't be generated.

**Comment by moritzsternemann** [comment]
Alright, using sorcery 👌

**Comment by kimdv** [comment]
Now on staging

Fixed in #155
